### ISSUE TITLE
C=GPIO Support

### ISSUE THREAD

**Issue by dorktronic** [cityxen/RelayTracker#1]
Hi!  This is such a cool project and a great idea!

I make the C=GPIO, a 32 I/O board for Commodore machines and I'd love to see it supported with RelayTracker.  I'm a 6502 coder as well and am happy to help make this happen.

https://www.ebay.com/itm/333269323919

Let me know if you're interested in that.

Cheers!
Sam

**Comment by deadline-cxn** [comment]
Hey,

Thanks for the message.
Yes! I would be willing to collaborate on this, and possibly modify the
program to work with it.
I never had heard of your GPIO device, but I like it... A lot!
Any chance you could send us one for testing?
Allright, I found your github repo and started thinking about how to
integrate it.

Cheers,
Seth

**Comment by dorktronic** [comment]
Ok great!  Yeah, I can send you a board for testing if you're in the US.  Go ahead and email your physical address to me: sales@dorktronic.com.

**Comment by deadline-cxn** [comment]
Closing issue, sent private email
